# Generate CHANGELOG.md and tag with version if package.json version was bumped

on:
  pull_request:
    branches: 
      - master
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
        ref: master
    - run: |
        echo The PR was merged
        echo Those are 2 last git log entries
        git log -2 | cat
        echo --------------------------------
        git tag | cat